### ISSUE TITLE
Ef core bug

### ISSUE THREAD

**Issue by kovlevi** [radimitrov/CSharpShellApp#134]
I just builded an apk (xamarin forms) with ef core and it throw the foolowing exception:
![Screenshot_20220508_160544_com companyname gothamstrategy](https://user-images.githubusercontent.com/90194413/167300078-2bfae0fc-f7d7-4973-9e66-be991aa7807d.jpg)

The code within my db context:

public GothamDbContext()
        {

              //DbSets
        	path = Path.Combine(firstPath,"data.db3");
        	//Database.EnsureDeleted();
        	Database.EnsureCreated();
        }
        
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
        	optionsBuilder.UseSqlite($"Filename={path}");
        }
        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
        	modelBuilder.Entity<CourtTrialScene>().Property(x => x.Questions).HasConversion(x => Serialize(x),x => Deserialize<List<string>>(x));
        	modelBuilder.Entity<FightScene>(x => 
        	{
        		x.Property(x => x.PoliceLocation).HasConversion(x => Serialize(x),x => Deserialize<List<int>>(x));
        		x.Property(x => x.EnemiesLocation).HasConversion(x => Serialize(x),x => Deserialize<List<int>>(x));
        	});
        	modelBuilder.Entity<InterrogationScene>().Property(x => x.Questions).HasConversion(x => Serialize(x),x => Deserialize<List<string>>(x));
        	modelBuilder.Entity<Villain>().Property(x => x.Aliases).HasConversion(x => Serialize(x),x => Deserialize<List<string>>(x));
        	modelBuilder.Entity<Work>().HasData(new WorkSeeder().Seed());
        	modelBuilder.Entity<Armor>().HasData(new ArmorSeeder().Seed());
        	modelBuilder.Entity<Weapon>().HasData(new WeaponSeeder().Seed());
        	
        }
        
        string Serialize<T>(T input)
        {
        	return JsonSerializer.Serialize(input,default);
        }
        
        T Deserialize<T>(string json)
        {
        	return JsonSerializer.Deserialize<T>(json,default);
        }

This happens in debug with seeding(hasdata in  Onmodelcreating, but I think it's not important) even if I uncomment Database.EnsureDeleted():

**Comment by kovlevi** [comment]
![Screenshot_20220508_161634_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/167300529-a2581e9b-229a-492e-91ec-82ea912efddd.jpg)

**Comment by kovlevi** [comment]
![Uploading Screenshot_20220508_170900_com.radinc.csharpshell.jpg…]()


Perhaps the problem is this, but I don't know the reason and it's fix. Please help me!

**Comment by kovlevi** [comment]
These are the pictures about the problem:

![Screenshot_20220508_170900_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/167302829-c05460b9-3125-4c34-bfb4-d61800766916.jpg)
![Uploading Screenshot_20220508_170847_com.radinc.csharpshell.jpg…]()
![Uploading Screenshot_20220508_170837_com.radinc.csharpshell.jpg…]()

**Comment by kovlevi** [comment]
![Screenshot_20220508_170847_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/167302850-3ffb85ad-95fe-4daf-a935-a0bb4bb11bb2.jpg)

**Comment by kovlevi** [comment]
![Uploading Screenshot_20220508_170837_com.radinc.csharpshell.jpg…]()

**Comment by kovlevi** [comment]
![Uploading Screenshot_20220508_170837_com.radinc.csharpshell.jpg…]()

**Comment by radimitrov** [comment]
I'm not sure about the entity error. Is it within C# Shell only? As in not when run as an independent app?
The initializer error is the property "init", I think. I'll add [this ](https://stackoverflow.com/questions/64749385/predefined-type-system-runtime-compilerservices-isexternalinit-is-not-defined) as a workaround for now. You can try it too.

**Comment by kovlevi** [comment]
And what about the first screenshot problem: the type initalizer 'Microsoft.EntityFrameworkCore.Internal.CoreStrings' threw exception? Do you have any idea about that why it happens or how can I solve it?

**Comment by radimitrov** [comment]
Maybe it is bundling a newer version of EntityFrameworkCore instead of the embedded one? I'll check. For now the app supports only 2.2.

**Comment by radimitrov** [comment]
No, just checked. It bundles into the APK what it is using - v2.2.

**Comment by kovlevi** [comment]
Yeah, I know and I have that 2.2.0 nuget package:

![Screenshot_20220508_214203_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/167313022-2429badd-75f4-4985-bb61-eba4ccbf1e92.jpg)

**Comment by radimitrov** [comment]
Then perhaps storage permissions? What is the root path?

**Comment by kovlevi** [comment]
FileSystem.AppDataDirectory - from xamarin essentials, this is where it creates the database(db3) file and I have storage permissions

![Screenshot_20220508_214846_com radinc csharpshell](https://user-images.githubusercontent.com/90194413/167313327-dca779c3-9536-4247-ae3e-37ad45b43644.jpg)

**Comment by radimitrov** [comment]
Then the problem isn't path or permissions.

**Comment by kovlevi** [comment]
the type initalizer 'Microsoft.EntityFrameworkCore.Internal.CoreStrings' threw exception - this is the exception that it throws/shows

**Comment by radimitrov** [comment]
Well, the exception makes some sense now. Notice the missing native library in the APK? I'll fix that tomorrow.
![eftest_apk](https://user-images.githubusercontent.com/56889141/167313823-23cba83e-5082-46df-944e-1bddefc947ec.png)

**Comment by kovlevi** [comment]
Yeah, I see that your test app didn't generated that selected file. Thank you, I'm waiting for the update then

**Comment by radimitrov** [comment]
It looks like an issue in the dependency resolver. In case I don't manage to fix it tomorrow then manually referencing this library should do it.
![sqlite_lib](https://user-images.githubusercontent.com/56889141/167315107-24e29b87-9b0f-4274-a485-b452682e8317.png)

**Comment by kovlevi** [comment]
Tried it, but it still throws the same error

**Comment by radimitrov** [comment]
Maybe there is something else too. But make sure the lib is actually in APK.
![apk_libs](https://user-images.githubusercontent.com/56889141/167315436-0cb176cc-3617-46c2-9f6b-505ff5ca7df9.png)

**Comment by kovlevi** [comment]
Yeah, I see it inside(I renamed .apk to .zip to see it):

![Screenshot_20220508_225711_com huawei filemanager](https://user-images.githubusercontent.com/90194413/167315549-0a3be789-3dbd-44fa-be63-2e56ec9ee56a.jpg)

**Comment by radimitrov** [comment]
Ok, at least that works. I will look over the dependency resolver tomorrow. Maybe the wrong framework version DLL for something is being embedded.

**Comment by kovlevi** [comment]
All right. Anyway thanks for your help

**Comment by kovlevi** [comment]
I think I found the problem. Look for this file(this path was in innerexception message):

![Screenshot_20220508_233152_com my eftest](https://user-images.githubusercontent.com/90194413/167316664-9e51c76f-393d-4f9c-8a8a-1cd7a121f902.jpg)

I don't see this file

**Comment by radimitrov** [comment]
It was mainly the dependency resolvers losing the scent. Should be working as expected in the next update.

**Comment by radimitrov** [comment]
Probably tomorrow. I need to make sure nothing was broken by this change.

**Comment by kovlevi** [comment]
Updated C# Shell, but the same exception still throws and that assemblies/Microsoft.EntityFrameworkCore.resources.dll still isn't not generated

**Comment by kovlevi** [comment]
That exception is fixed. But now this is the new Exception it throws:

![Screenshot_20220510_123447_com companyname eftest](https://user-images.githubusercontent.com/90194413/167609784-fddbad83-fbfc-4a4b-aaae-c023866693a0.jpg)

This is my test code by the way:

using System;
using System.IO;
using Xamarin.Forms;
using Microsoft.EntityFrameworkCore.Sqlite;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Xamarin.Essentials;

namespace EfTest
{
	public partial class App : Application
	{
		public App()
		{
			InitializeComponent();
			MainPage = new MainPage();
			try
			{
			    PersonDbContext context = new PersonDbContext();
			    Show("ok");
			}
			catch(Exception ex)
			{
				Show(ex.Message);
			}
		}
		
		async void Show(string s)
	    {
		   await App.Current.MainPage.DisplayAlert("",s,"OK");
	    }
	}
	
	class Person
	{
		[Key]
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public long Id{get;set;}
		public string Name{get;set;}
	}
	
	class PersonDbContext : DbContext
	{
		public DbSet<Person> People{get;set;}
		
		public PersonDbContext()
		{
			Database.EnsureCreated();
		}
		
		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlite("Filename=/storage/emulated/0/data.db3");
		}
	}
}

**Comment by kovlevi** [comment]
All right then I will wait for the fix, hope you can fix all ef core bugs
