### ISSUE TITLE
Ef core bug

### ISSUE THREAD

**Issue by sedoLevi609** [radimitrov/CSharpShellApp#238]

**Comment by sedoLevi609** [comment]
I tried with ef core 7 with internal reference System.ComponentModel.DataAnnotations

First of all I get these warnings(not sure if it's important, as I see all warnings are the same for some reason and the end contains an information(runtime policy may be suplied or what)):

[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.Linq.Expressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Linq.Expressions', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.Data.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore.Sqlite' matches identity 'System.Data.Common, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Data.Common', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.Linq.Expressions, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.Linq.Expressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Linq.Expressions', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy
[Warning] CS1701: Assuming assembly reference 'System.ComponentModel, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Microsoft.EntityFrameworkCore' matches identity 'System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.ComponentModel', you may need to supply runtime policy

If I try running the project with a Class that has eg. only string property in it it throws this exception(eg. with only int it works):



System.InvalidOperationException: NullabilityInfoContext is not supported in the current application because 'System.Reflection.NullabilityInfoContext.IsSupported' is set to false. Set the MSBuild Property 'NullabilityInfoContextSupport' to true in order to enable it.
   at System.Reflection.NullabilityInfoContext.EnsureIsSupported()
   at System.Reflection.NullabilityInfoContext.Create(PropertyInfo propertyInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableConventionBase.IsNonNullableReferenceType(IConventionModelBuilder modelBuilder, MemberInfo memberInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableReferencePropertyConvention.Process(IConventionPropertyBuilder propertyBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.NonNullableReferencePropertyConvention.ProcessPropertyAdded(IConventionPropertyBuilder propertyBuilder, IConventionContext`1 context)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnPropertyAdded(IConventionPropertyBuilder propertyBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnPropertyAddedNode.Run(ConventionDispatcher dispatcher)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.DelayedConventionScope.Run(ConventionDispatcher dispatcher)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelInitialized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelInitialized(IConventionModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model..ctor(ConventionSet conventions, ModelDependencies modelDependencies, ModelConfiguration modelConfiguration)
   at Microsoft.EntityFrameworkCore.ModelBuilder..ctor(ConventionSet conventions, ModelDependencies modelDependencies, ModelConfiguration modelConfiguration)
   at Microsoft.EntityFrameworkCore.ModelConfigurationBuilder.CreateModelBuilder(ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, ModelDependencies modelDependencies)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, ModelCreationDependencies modelCreationDependencies, Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel(Boolean designTime)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__8_4(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyTo

**Comment by sedoLevi609** [comment]
[BaseDatabase.zip](https://github.com/radimitrov/CSharpShellApp/files/10755879/BaseDatabase.zip)

**Comment by sedoLevi609** [comment]
Please help!

**Comment by radimitrov** [comment]
It looks like you need to install sqlite-pclraw package.

The warnings shouldn't matter as .NET 7 should be backwards compatible to .NET 6 libraries. Some dependency must be targeting that.

**Comment by sedoLevi609** [comment]
Which sqlite-pclraw package? Can't see package with that name.
![packages](https://user-images.githubusercontent.com/51722783/219499873-17f6ae09-7b95-4db7-81ef-3d7691e5dad6.jpg)

**Comment by radimitrov** [comment]
SQLitePCLRaw.lib.e_sqlite3 should work, but I think SQLitePCLRaw.bundle_green is best since it also has that as a dependency amongst others.

**Comment by sedoLevi609** [comment]
None of the two worked for me without compiling apk(didn't tried with compiled apk)

**Comment by radimitrov** [comment]
Your project compiles when I add them. Beyond that if you're on Android >= 11 then there don't have file access to "/storage/emulated/0"

**Comment by sedoLevi609** [comment]
Are you sure that this doesn't important on my side:

System.InvalidOperationException: NullabilityInfoContext is not supported in the current application because 'System.Reflection.NullabilityInfoContext.IsSupported' is set to false. Set the MSBuild Property 'NullabilityInfoContextSupport' to true in order to enable it? 

And the packages you mentioned solve this issue? Just because I can't get the project to work(I have android 10,as I know it)

**Comment by sedoLevi609** [comment]
And this exception is the problem in  a compiled apk:

 
![error](https://user-images.githubusercontent.com/51722783/219808067-6dbac052-f10d-4fb0-9118-3f000bbe7543.jpg)

**Comment by sedoLevi609** [comment]
And if can't create file in /storage/emulated/0,where can I create files on android 11?

**Comment by sedoLevi609** [comment]
@radimitrov Please help!

**Comment by radimitrov** [comment]
I'll add a Nullable option in the project settings. That should fix the NotSupportedException.
I'll have to look into the APK issue more. It might not be adding some dependencies to the apk implicitly.

**Comment by sedoLevi609** [comment]
If I set Nullable to Enable still not works, same exception thrown(in the not compiled apk).

**Comment by sedoLevi609** [comment]
@radimitrov So the Nullable project setting not works for me(for entity framework 7)

**Comment by radimitrov** [comment]
@sedoLevi609 The APK issue is an because an implicit dependency (Microsoft.EntityFrameworkCore.Relational) isn't being added to it. I'll probably fix the root cause within a few days.
You shouldn't be getting a "System.InvalidOperationException: NullabilityInfoContext is not supported" now. I haven't.
However I'm getting an app crash with Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) on the thread pool.  You might have an error causing infinite recursion somewhere.

**Comment by sedoLevi609** [comment]
@radimitrov I don't think I wrote code that makes infinite recursion. Maybe this is related with entity framework somehow?

**Comment by sedoLevi609** [comment]
@radimitrov I also still has the NullabilityContextSupported error:


https://user-images.githubusercontent.com/51722783/219968982-1f66ab94-3187-4592-b06b-223969a5f438.mp4

**Comment by radimitrov** [comment]
@sedoLevi609  I got it working. Looks like it also needed `<NullabilityInfoContextSupport>true</NullabilityInfoContextSupport>` in C# Shell itself.

**Comment by sedoLevi609** [comment]
@radimitrov Starting app from C# Shell works now, but compiled apk still not find UseSqlite method,don't know if you tried to solve this problem yet(missing Microsoft.EntityFrameworkCore.Relational dependency)

**Comment by radimitrov** [comment]
@sedoLevi609 I haven't yet. If you manually add the packages it might be a workaround for now.

**Comment by sedoLevi609** [comment]
I added as nuget(which also adds the reference as I see in references),but same exception. Or I need to add the dependency in file manager manually? If yes, where can I put that dll?

**Comment by radimitrov** [comment]
@sedoLevi609 That should work in theory since it has to be an issue with the app's packages code, but it will take a while to do it for every dependency.

**Comment by sedoLevi609** [comment]
@radimitrov These are the references that are added via nuget:

![Screenshot_20230223_162012_com radinc csharpshell](https://user-images.githubusercontent.com/51722783/220950014-126cd974-c3e9-474f-879b-4af3454e6433.jpg)

**Comment by sedoLevi609** [comment]
@radimitrov Maybe I found the issue:
I added this code to my app to show entityframeworkcore dependencies(dlls):

File.WriteAllText("/storage/emulated/0/dlls.txt",String.Join('\n',AppDomain.CurrentDomain.GetAssemblies().Where(x => x.GetName().Name.ToLower().Contains("entityframework")).SelectMany(asm => asm.GetModules()).Select(module => module.Name)));

The result when just running in your app:

![Screenshot_20230227_094344_smartsolutions explorer tools fileexplorer](https://user-images.githubusercontent.com/51722783/221516091-bb9daab5-06b8-483a-8f5a-851fc877fdf5.jpg)

And the result with the compiled apk:

![Screenshot_20230227_094226_smartsolutions explorer tools fileexplorer](https://user-images.githubusercontent.com/51722783/221516184-6638119d-7724-4072-a77f-a3feee352a2c.jpg)

**Comment by sedoLevi609** [comment]
Besides since ef core is a nuget package, I think maybe all nuget packages can have this bug, but I don't know for sure, just a guess.

**Comment by sedoLevi609** [comment]
@radimitrov Updated plugin and C# Shell, but nothing changed in case you implemented adding references to entityframeworkcore. But you should take a look on the last 2 messages on this issue, maybe it will help you solve the bug

**Comment by radimitrov** [comment]
@sedoLevi609  Open the APK with a zip tool. The assemblies are there. The problem isn't as simple as that. And other packages work.

**Comment by kovlevi** [comment]
@radimitrov Any luck fixing this bug?

**Comment by radimitrov** [comment]
@kovlevi No. Fixed another issue with the libs/so directory, but it isn't that.

**Comment by radimitrov** [comment]
@sedoLevi609 @kovlevi This should now work after today's plugin update.

**Comment by sedoLevi609** [comment]
@radimitrov Thank you, it works now. By the way sedoLevi609 and kovlevi users are both me, just I have 2 Accounts, just sometimes I forgot to log in back with the right one(sedoLevi609)
