### ISSUE TITLE
Clicking on error message takes to the wrong file

### ISSUE THREAD

**Issue by KUNGERMOoN** [radimitrov/CSharpShellApp#281]
Steps to reproduce
- Download and copy this project: https://drive.google.com/file/d/1wPQZbitI7FnC7ZRnm0ZeoUzer3TvMaUT/view?usp=drivesdk
- Open the FloatToIntConverter.cs file
- Press run (you should see an error in the file ColorList.xaml)
- click the error message
- you will see the contents of the ColorList.xaml file, but without any syntax coloring and it'll show errors as if it was a .cs file (and not a xaml file)
- If you open the file list at the top of the page, it'll say that it's actually FloatToIntConverter.cs file
- Doing and saving any changes will apply them to the ColorList.xaml file
- obviously this problem won't cause any confusion when the file in which the error appeared was the file opened before clicking on the error message

This *might* be expected behaviour, but it really confused me as to which file I was editing and why syntax coloring didn't work the first few times it happened to me

![IMG_20230501_182007.jpg](https://user-images.githubusercontent.com/60297336/235486913-35cc7e2e-61ce-4288-a15f-c773b972e0c9.jpg)
![IMG_20230501_182212.jpg](https://user-images.githubusercontent.com/60297336/235486981-128cd5a7-2a91-41bc-ad16-34a1b416d223.jpg)
![IMG_20230501_181936.jpg](https://user-images.githubusercontent.com/60297336/235487010-2692629b-3b2d-4b03-b63f-50bc8af681c6.jpg)

**Comment by radimitrov** [comment]
This should all be fixed in the next update.

**Comment by KUNGERMOoN** [comment]
> This should all be fixed in the next update.
Hi, @radimitrov  most of the stuff is working, but on the file navbar it still shows the wrong file is open:

![Screenshot_20230927-213454~2](https://github.com/radimitrov/CSharpShellApp/assets/60297336/ebf212e3-50ce-4ac3-a951-39a6d1c16013)
